GET http://localhost:3000/api/companies

###
GET http://localhost:3000/api/companies?page=0&limit=10&order=employeeHighest

###
GET http://localhost:3000/api/companies?page=0&limit=10&order=investmentHighest

###
GET http://localhost:3000/api/companies?page=0&limit=10&order=revenueHighest

###
GET http://localhost:3000/api/companies?page=0&limit=10&order=revenueLowest

###
GET http://localhost:3000/api/companies?page=0&limit=10&order=employeeHighest

###

GET http://localhost:3000/api/companies?page=0&limit=10&order=revenueHighest&search=스타트업%20A

###

GET http://localhost:3000/api/companies/5d4e1c26-6f16-464e-829f-8fcf442634e3
###


GET http://localhost:3000/api/companies/rank/9d0k1c26-6f16-464e-829f-8fcf442634e3?order=totalInvestmentHighest
###
GET http://localhost:3000/api/companies/rank/9d0k1c26-6f16-464e-829f-8fcf442634e3?order=totalInvestmentLowest
###
GET http://localhost:3000/api/companies/rank/9d0k1c26-6f16-464e-829f-8fcf442634e3?order=revenueHighest
###
GET http://localhost:3000/api/companies/rank/9d0k1c26-6f16-464e-829f-8fcf442634e3?order=revenueLowest
###
GET http://localhost:3000/api/companies/rank/9d0k1c26-6f16-464e-829f-8fcf442634e3?order=employeeHighest
###
GET http://localhost:3000/api/companies/rank/9d0k1c26-6f16-464e-829f-8fcf442634e3?order=employeeLowest
###