GET http://localhost:3000/api/companies

###
GET http://localhost:4000/api/companies?page=0&limit=10&order=employeeHighest

###
GET http://localhost:3000/api/companies?page=0&limit=10&order=investmentHighest

###
GET http://localhost:3000/api/companies?page=0&limit=10&order=revenueHighest

###
GET http://localhost:3000/api/companies?page=0&limit=10&order=revenueLowest

###
GET http://localhost:3000/api/companies?page=0&limit=10&order=employeeHighest

###

GET http://localhost:3000/api/companies?page=0&limit=10&order=revenueHighest&search=스타트업%20A

###

GET http://localhost:3000/api/companies/e56b0ceb-bb30
###


GET http://localhost:3000/api/companies/9d0k1c26-6f16-464e-829f-8fcf442634e3/rank?order=totalInvestmentHighest
###
GET http://localhost:3000/api/companies/9d0k1c26-6f16-464e-829f-8fcf442634e3/rank?order=totalInvestmentLowest
###
GET http://localhost:3000/api/companies/9d0k1c26-6f16-464e-829f-8fcf442634e3/rank?order=revenueHighest
###
GET postgresql://viewmystartup_user:54wR0ep5WSjM9bzBPbwbtCAZlbtKF6hn@dpg-crv4r61u0jms73akoihg-a.singapore-postgres.render.com/viewmystartup/api/companies/9d0k1c26-6f16-464e-829f-8fcf442634e3/rank?order=revenueLowest
###
GET http://localhost:3000/api/companies/9d0k1c26-6f16-464e-829f-8fcf442634e3/rank?order=employeeHighest
###
GET http://localhost:3000/api/companies/9d0k1c26-6f16-464e-829f-8fcf442634e3/rank?order=employeeLowest
###