GET http://localhost:3000/api/companies

###

GET http://localhost:3000/api/companies?page=0&limit=10&order=revenueHighest&search=스타트업%20A

###

GET http://localhost:3000/api/companies/3cd245e0-f8b2-4a95-a10f-6dfc68e8c2d2