GET http://localhost:4000/api/companies/e56b0ceb-bb30-bbec-805e-d5dc7412dcb1/investments

###
PATCH http://localhost:4000/api/investments/ef7dcecf-1796-48f1-aa67-2430c71ea067
Content-Type: application/json

{
  "investorName": "테스트",
  "amount": "900000000",
  "comment": "정말 훌륭한 기업입니다 화이팅",
  "password": "password123123"
}

###
DELETE http://localhost:4000/api/investments/1645a4cb-0fc6-4ce6-8466-a4ba00ef5b98