GET http://localhost:3000/api/companies/counts

###
GET http://localhost:3000/api/companies/counts?page=0&limit=10&order=myCountHighest

###
GET http://localhost:3000/api/companies/counts?order=myCountLowest

###
GET http://localhost:3000/api/companies/counts?order=comparedHighest

###
GET http://localhost:3000/api/companies/counts?order=comparedLowest

###
PATCH  http://localhost:3000/api/companies/c7g1e1c26-6f16-464e-829f-8fcf442634e3/my-chosen-count

###
PATCH  http://localhost:3000/api/companies/c7g1e1c26-6f16-464e-829f-8fcf442634e3/compared-chosen-count