GET http://localhost:3000/api/investments

###

GET http://localhost:3000/api/investments/c14n1e1c26-6f16-464e-829f-8fcf442634e3

###

PATCH http://localhost:3000/api/investments/c14n1e1c26-6f16-464e-829f-8fcf442634e3
Content-Type: application/json

{
  "simulatedInvest":"200000000"
}